### ISSUE TITLE
请问 运行npm run hm-serve-all后报错，是怎么回事呢？

### ISSUE THREAD

**Issue by huwanlong** [Joycezhangw/qiankun-vue-demo#7]
请问运行npm run hm-serve-all后页面分别报如下错误

Module not found: Error: Can't resolve './modules' in 'E:\HBuilderProjects\qiankun-vue-demo\master\src\store'

Module not found: Error: Can't resolve './modules' in 'E:\HBuilderProjects\qiankun-vue-demo\subapp-test\src\store'

**Comment by Joycezhangw** [comment]
> 请问运行npm run hm-serve-all后页面分别报如下错误
> 
> Module not found: Error: Can't resolve './modules' in 'E:\HBuilderProjects\qiankun-vue-demo\master\src\store'
> 
> Module not found: Error: Can't resolve './modules' in 'E:\HBuilderProjects\qiankun-vue-demo\subapp-test\src\store'

你好，请分别在`master`和`subapp-test`应用下的 `src/store` 目录下新建 `modules`空目录。因为在`store/index.js`有检索`modules`目录，并导出所有状态的操作。
